"""Add phase1 collection state

Revision ID: 09a64bf9b2ea
Revises: 34908a499f15
Create Date: 2026-04-25 23:30:03.227302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09a64bf9b2ea'
down_revision: Union[str, Sequence[str], None] = '34908a499f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'open'"), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'resolved', 'ignored')", name='ck_review_queue_status'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_queue_status', 'review_queue', ['status'], unique=False)
    op.add_column('items', sa.Column('content_simhash', sa.String(length=16), nullable=True))
    op.add_column('sources', sa.Column('etag', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('last_modified', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('fetch_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_constraint('ck_items_status', 'items', type_='check')
    op.create_check_constraint(
        'ck_items_status',
        'items',
        "status IN ('raw', 'clean', 'extract_failed', 'summarized', 'draft_ready', 'published')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_items_status', 'items', type_='check')
    op.create_check_constraint(
        'ck_items_status',
        'items',
        "status IN ('raw', 'clean', 'summarized', 'draft_ready', 'published')",
    )
    op.drop_column('sources', 'fetch_count')
    op.drop_column('sources', 'last_modified')
    op.drop_column('sources', 'etag')
    op.drop_column('items', 'content_simhash')
    op.drop_index('ix_review_queue_status', table_name='review_queue')
    op.drop_table('review_queue')
    # ### end Alembic commands ###
